/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CustomerMenu;
import Admin.ObjWriteRead;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author james
 */
public class CustomerUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerUI
     */
    int messageNo;
    
     public CustomerUI() {
        try {
            initComponents();
            messageNo = Message.getMessageNo(CustomerLogin.customerID);
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
            // Handle the exception, e.g., show an error dialog and exit the application
            JOptionPane.showMessageDialog(this, "Error initializing CustomerUI: " + ex.getMessage());
            System.exit(1);
        }
        messNo.setText(String.valueOf(messageNo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewMenu = new javax.swing.JButton();
        orderHistory = new javax.swing.JButton();
        orderStatus = new javax.swing.JButton();
        transactionHistory = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        messNo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewMenu.setText("View menu");
        viewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMenuActionPerformed(evt);
            }
        });

        orderHistory.setText("Check order history");
        orderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistoryActionPerformed(evt);
            }
        });

        orderStatus.setText("Check order status");
        orderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderStatusActionPerformed(evt);
            }
        });

        transactionHistory.setText("Check transaction history");
        transactionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionHistoryActionPerformed(evt);
            }
        });

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View notification");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("You have");

        messNo.setText("0");

        jLabel4.setText("notification/s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transactionHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messNo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewMenu)
                    .addComponent(jLabel2)
                    .addComponent(messNo)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderStatus)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addComponent(orderHistory)
                .addGap(32, 32, 32)
                .addComponent(transactionHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMenuActionPerformed
        // TODO add your handling code here:
        customerMenu menu = new customerMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewMenuActionPerformed

    private void orderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistoryActionPerformed
        // TODO add your handling code here:
            OrderHistory history = new OrderHistory();
            history.setVisible(true);
            dispose();
    }//GEN-LAST:event_orderHistoryActionPerformed

    private void orderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderStatusActionPerformed
        // TODO add your handling code here:
        OrderStatus stat = new OrderStatus();
        stat.setVisible(true);
    }//GEN-LAST:event_orderStatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        File myObj = new File("currentCustomer.txt"); 
        myObj.delete();
        CustomerLogin login = new CustomerLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(messageNo==0){
            JOptionPane.showMessageDialog(null, "There is no notification!");
        }
        else{
            try{
            List<Message> Messages = Message.getMessages(CustomerLogin.customerID);
            for(int i=0;i<Messages.size();i++){
                if(Messages.get(i).getNotify()==Message.messageType.NOTIFICATION){
                    String content = Messages.get(i).getMessage();
                    String messageID = Messages.get(i).getMessageID();
                    JOptionPane.showMessageDialog(null, content);
                    Message.markMessageAsRead(messageID);
                }
                else if(Messages.get(i).getNotify()==Message.messageType.FOODORDER){
                    String content = Messages.get(i).getMessage();
                    String messageID = Messages.get(i).getMessageID();
                    String orderID = Messages.get(i).getOrderID();
                    String[] customOptions = { "Confirm","Cancel"};
        
                    int confirmation = JOptionPane.showOptionDialog(
        null,
              content,
               "Confirmation",
            JOptionPane.YES_NO_OPTION,
           JOptionPane.QUESTION_MESSAGE,
                null, // Use default icon
              customOptions, // Use custom button labels
                    customOptions[0] // Default selection
                    );
                    if(confirmation==0){
                        OrderFile.setOrderStatus(orderID, OrderFile.OrderStatus.COMPLETED);
                        Message.markMessageAsRead(messageID);
                    }
                }
            }
            }
            catch(IOException e){
                
            }
            catch (ClassNotFoundException ex) {
                
            }
        }
        
        messageNo = 0;
        messNo.setText(String.valueOf(messageNo));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void transactionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionHistoryActionPerformed
        // TODO add your handling code here:
        TransactionHistory tran = new TransactionHistory();
        tran.setVisible(true);
        dispose();
    }//GEN-LAST:event_transactionHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel messNo;
    private javax.swing.JButton orderHistory;
    private javax.swing.JButton orderStatus;
    private javax.swing.JButton transactionHistory;
    private javax.swing.JButton viewMenu;
    // End of variables declaration//GEN-END:variables
}
